### ISSUE TITLE
Can't run the example

### ISSUE THREAD

**Issue by wenhui-prudencemed** [AeonLucid/AndroidNativeEmu#1]
Hi,

I follow the Readme file to run the example.py in Ubuntu 16.04 + python 3.7 but failed to load the dynamic library.
here is the log:

sudo python3.7 example.py

Traceback (most recent call last):
  File "example.py", line 7, in <module>
    from androidemu.emulator import Emulator
  File "/home/prudencemed/AndroidNativeEmu/samples/androidemu/emulator.py", line 12, in <module>
    from androidemu.hooker import Hooker
  File "/home/prudencemed/AndroidNativeEmu/samples/androidemu/hooker.py", line 1, in <module>
    from keystone import Ks, KS_ARCH_ARM, KS_MODE_THUMB
  File "/usr/local/lib/python3.7/dist-packages/keystone/__init__.py", line 4, in <module>
    from .keystone import Ks, ks_version, ks_arch_supported, version_bind, debug, KsError, __version__
  File "/usr/local/lib/python3.7/dist-packages/keystone/keystone.py", line 75, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.

Could you help for this?

Thanks,
Wenhui

**Comment by achenglike** [comment]
> Hi,
> 
> I follow the Readme file to run the example.py in Ubuntu 16.04 + python 3.7 but failed to load the dynamic library.
> here is the log:
> 
> sudo python3.7 example.py
> 
> Traceback (most recent call last):
> File "example.py", line 7, in 
> from androidemu.emulator import Emulator
> File "/home/prudencemed/AndroidNativeEmu/samples/androidemu/emulator.py", line 12, in 
> from androidemu.hooker import Hooker
> File "/home/prudencemed/AndroidNativeEmu/samples/androidemu/hooker.py", line 1, in 
> from keystone import Ks, KS_ARCH_ARM, KS_MODE_THUMB
> File "/usr/local/lib/python3.7/dist-packages/keystone/**init**.py", line 4, in 
> from .keystone import Ks, ks_version, ks_arch_supported, version_bind, debug, KsError, **version**
> File "/usr/local/lib/python3.7/dist-packages/keystone/keystone.py", line 75, in 
> raise ImportError("ERROR: fail to load the dynamic library.")
> ImportError: ERROR: fail to load the dynamic library.
> 
> Could you help for this?
> 
> Thanks,
> Wenhui


hi,you resolved this issue? could tell me how ? Thx
