### ISSUE TITLE
If Jni_Onload is not in the native library, ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type

### ISSUE THREAD

**Issue by qiuxuewen** [AeonLucid/AndroidNativeEmu#20]
If Jni_Onload is not in the native library, ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type,

self.mu.emu_start(addr, stop_pos - 1)
  File "/usr/local/lib/python3.7/dist-packages/unicorn/unicorn.py", line 286, in emu_start
    status = _uc.uc_emu_start(self._uch, begin, until, timeout, count)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type

**Comment by AeonLucid** [comment]
Then don't call `Jni_Onload`.
