### ISSUE TITLE
have some trouble in add env->EnsureLocalCapacity

### ISSUE THREAD

**Issue by colzenleft** [AeonLucid/AndroidNativeEmu#25]
maybe added in jni_env.py

but I am not sure, there is a big table under hooker.write_function_table but the index is not the same as JNIEnv's offset. how could I add EnsureLocalCapacity in it ?

**Comment by AeonLucid** [comment]
According to https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/functions.html the index of `EnsureLocalCapacity` is `26`, [which is what I have](https://github.com/AeonLucid/AndroidNativeEmu/blob/fbcb9507d000df252b23a6efd7cedcf40427eb7b/androidemu/java/jni_env.py#L53).

Just add your code in here https://github.com/AeonLucid/AndroidNativeEmu/blob/fbcb9507d000df252b23a6efd7cedcf40427eb7b/androidemu/java/jni_env.py#L536.

**Comment by f8lft** [comment]
Most of the time would be enough just to return 0.

**Comment by colzenleft** [comment]
thanks for all
