### ISSUE TITLE
native_write_args argument passing in wrong order?

### ISSUE THREAD

**Issue by flankerhqd** [AeonLucid/AndroidNativeEmu#29]
Hi:

Seems two questions in `native_write_args`:

1. 
https://github.com/AeonLucid/AndroidNativeEmu/blob/5542f522edf04de40dd5f7937d43300e22f401d7/androidemu/java/helpers/native_method.py#L35

why substract STACK_OFFSET twice?

2.  args[4] should be at [SP], args[5] at [SP+4], however in `native_write_args`, parameters are passed in wrong order. args[4] is at higher address

**Comment by AeonLucid** [comment]
I'll take a look at this

**Comment by AeonLucid** [comment]
Seems like this is indeed wrong.

```cpp
const char *one = env->GetStringUTFChars(one_, 0);
const char *two = env->GetStringUTFChars(two_, 0);
const char *three = env->GetStringUTFChars(three_, 0);
const char *four = env->GetStringUTFChars(four_, 0);
const char *five = env->GetStringUTFChars(five_, 0);
const char *six = env->GetStringUTFChars(six_, 0);
```

```python
res = emulator.call_symbol(module, 'testSixArg', emulator.java_vm.jni_env.address_ptr, 0x00, 'One', 'Two', 'Three', 'Four', 'Five', 'Six')
```

```
JNIEnv->GetStringUtfChars(1, 0) was called
=> One
JNIEnv->GetStringUtfChars(2, 0) was called
=> Two
JNIEnv->GetStringUtfChars(5, 0) was called
=> Five
JNIEnv->GetStringUtfChars(4, 0) was called
=> Four
JNIEnv->GetStringUtfChars(3, 0) was called
=> Three
JNIEnv->GetStringUtfChars(0, 0) was called
```

**Comment by AeonLucid** [comment]
https://github.com/AeonLucid/AndroidNativeEmu/blob/b8ed68d7e829115d131bc789ee07b1c8b21d7f89/androidemu/java/helpers/native_method.py#L43
