### ISSUE TITLE
hook dlopen() function has a error

### ISSUE THREAD

**Issue by 0xE4s0n** [AeonLucid/AndroidNativeEmu#30]
**androidemu/native/hooks.py line56**
`lib = os.path.realpath(os.path.join(__file__, '..', '..', '..', 'samples', 'example_binaries', 'libvendorconn.so'))`
**should be replaced to**
`lib = os.path.realpath(os.path.join(__file__, '..', '..', '..', '..', 'samples', 'example_binaries', 'libvendorconn.so'))`

Otherwise,the path will be replace to `AndroidNativeEmu-master\samples\samples\example_binaries\libvendorconn.so`

**Comment by AeonLucid** [comment]
Are you sure? How can `samples` be in there twice if there is no `samples` in the `androidemu/native/hooks.py` path?
It works fine for me.

**Comment by 0xE4s0n** [comment]
Sorry,I made a mistake.There were some error when i 'import'. I have moved `androidenu` into `samples`.  
Thank you for your work for this.
