### ISSUE TITLE
FileSystem Syscall:OverflowError: int too big to convert

### ISSUE THREAD

**Issue by FinchZ** [AeonLucid/AndroidNativeEmu#42]
![QQ截图20200706111507](https://user-images.githubusercontent.com/46061991/86552459-aac25800-bf7a-11ea-942b-113f011b6b24.png)

uc.mem_write(buf_ptr + 12, int(stat.st_ino).to_bytes(4, byteorder='little'))
OverflowError: int too big to convert

**Comment by satng** [comment]
mac 下遇到过这个问题，这行注释掉，一般情况下没影响。 有影响就到linux下调试

**Comment by FinchZ** [comment]
不错，谢谢兄弟，还真能用。不过还是希望修复一下这个小bug。
