### ISSUE TITLE
请问您什么时候破解的抖音，破解抖音版本号是多少啊？load_library函数好像不适应现在新版的libcms.so了。

### ISSUE THREAD

**Issue by Killerkk** [AeonLucid/AndroidNativeEmu#44]
可否讨论一下？新版的libcms.so文件是否需要重新写整个AndroidNativeEmu工具（手动比心

**Comment by AeonLucid** [comment]
English

**Comment by Killerkk** [comment]
Qǐngwèn nín shénme shíhòu pòjiě de dǒu yīn, pòjiě dǒu yīn bǎnběn hào shì duōshǎo a?Load_library hánshù hǎoxiàng bù shìyìng xiànzài xīnbǎn de libcms.Sole. 

Kěfǒu tǎolùn yīxià? Xīnbǎn de libcms.So wénjiàn shìfǒu xūyào chóngxīn xiě zhěnggè AndroidNativeEmu gōngjù (shǒudòng bǐ xīn
展开
116/5000
When did you crack the Douyin and what is the version number of the cracked Douyin? The load_library function does not seem to be suitable for the new version of libcms.so.

Can you discuss it? Does the new version of the libcms.so file need to rewrite the entire AndroidNativeEmu tool (manual comparison

**Comment by satng** [comment]
Looking forward to it
