### ISSUE TITLE
Do you know how to deal with the return value in the parameter?

### ISSUE THREAD

**Issue by Humenger** [AeonLucid/AndroidNativeEmu#51]
![8f721232e771e85d927252780cee52c](https://user-images.githubusercontent.com/27600008/99376422-e1808580-28ff-11eb-8411-b70b5f89eff1.png)
The last parameter of the function above is the return value.
![QQ截图20201117180441](https://user-images.githubusercontent.com/27600008/99376606-1c82b900-2900-11eb-9240-a0acf95aca4b.png)
But here only get the return value from R0.

**Comment by AeonLucid** [comment]
You put in a an array reference just like normally.

**Comment by ihbing** [comment]
![image](https://user-images.githubusercontent.com/27600008/99462373-7fab3480-296e-11eb-85bb-dc501770de64.png)
I have tested it and cannot get the return value from the out variable.

**Comment by ihbing** [comment]
![image](https://user-images.githubusercontent.com/27600008/99463350-7c18ad00-2970-11eb-8721-4eccd138739a.png)
![image](https://user-images.githubusercontent.com/27600008/99463388-95b9f480-2970-11eb-9683-bfaf1108b3a6.png)
This is my temporary solution, I don’t know if you have a better solution.
