### ISSUE TITLE
Bug with Java ClassFieldDef translated to class 'type'

### ISSUE THREAD

**Issue by ii64** [AeonLucid/AndroidNativeEmu#52]
It looks like something wrong with the Class set field value, if i do ClassFieldDef(..., ignore=True) the error's gone, but this case i want to set the field value, here is the error, the data field is string, but translated to `type`

instead of returning `ref.value` for string, this function return the type of the `ref.value` 
https://github.com/AeonLucid/AndroidNativeEmu/blob/bdcfea02d9ab93c98d78d53b5f59de7c00175cf7/androidemu/java/jni_env.py#L579-L585
`
![image](https://user-images.githubusercontent.com/26342994/100716316-1a822500-33eb-11eb-88f8-936eaf73f369.png)
![image](https://user-images.githubusercontent.com/26342994/100716371-2a016e00-33eb-11eb-97cd-c952896bce01.png)

**Comment by maiyao1988** [comment]
which version of libcms did you use?

**Comment by ii64** [comment]
Latest Tiktok Lite version, anyway this issue is solved.

**Comment by ii64** [comment]
I end up using this hack, glad it works
![image](https://user-images.githubusercontent.com/26342994/100776879-aa4dc080-3437-11eb-8fd5-65d59f14a3d0.png)

**Comment by ii64** [comment]
@maiyao1988 your ExAndroidNativeEmu working perfectly (although)
